version: '3.8'

services:
  postgres-db:
    image: postgres:17-alpine
    container_name: smart_production_planner_db
    environment:
      POSTGRES_USER: rafael_planner
      POSTGRES_PASSWORD: planner_password
      POSTGRES_DB: smart_production_planner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
